// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Andre R",
            "email": "andrerafli83@gmail.com"
        },
        "license": {
            "name": "dreowsy"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/stocklab-api//v1/products/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan list product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Product list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ProductSuccessResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.ProductFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api//v1/products/update/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update product (PATCH semantics)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Update product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "category_id",
                        "name": "category_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "brand",
                        "name": "brand",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "price",
                        "name": "price",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Product image",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ProductUpdateSuccessResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.ProductUpdateFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.ProductUpdateFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/categories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all category in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Get list of category",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.CategorySuccessResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.CategoryFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/categories/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a category",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Create category for products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.CategoryCreateSuccessResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.CategoryCreateFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.CategoryCreateFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/categories/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.CategoryDeleteSuccessResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.CategoryDeleteFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.CategoryDeleteFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/categories/update/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing category product data",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Update category product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.CategoryUpdateSuccessResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.CategoryUpdateFailResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services.CategoryUpdateFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.CategoryUpdateFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/dashboard/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan data dashboard",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Dashboard data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.DashboardSuccessResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.DashboardFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/login": {
            "post": {
                "description": "Login to the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.AuthLoginParamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.AuthLoginSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/services.AuthLoginFailResponse"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/products/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a product",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Create product for products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "category_id",
                        "name": "category_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "brand",
                        "name": "brand",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "price",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Product image",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ProductCreateData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.ProductCreateFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.ProductCreateFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/products/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete product by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Delete product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ProductDeleteSuccessResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.ProductDeleteFailResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services.ProductDeleteFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.ProductDeleteFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/products/detail/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan detail product berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Product detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ProductDetailSuccessResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.ProductDetailFailResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services.ProductDetailFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.ProductDetailFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/transactions/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a transaction for stock movements",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Create transaction stocks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "product_id",
                        "name": "product_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "quantity",
                        "name": "quantity",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "move_type",
                        "name": "move_type",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.TransactionCreateData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.TransactionCreateFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.TransactionCreateFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/transactions/list": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List a transaction for stock movements",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "List transaction stocks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.TransactionListData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.TransactionListFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.TransactionListFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all users in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get list of users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.UserListSuccessResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.UserListFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/users/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new user and upload avatar",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user with avatar",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "phone",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Avatar image",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.UserCreateSuccessResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.UserCreateFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.UserCreateFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/users/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.UserDeleteSuccessResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.UserDeleteFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.UserDeleteFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/users/detail/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a single user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get detail of a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.UserDetailSuccessResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services.UserDetailFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.UserDetailFailResp"
                        }
                    }
                }
            }
        },
        "/stocklab-api/v1/users/update/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing user and optionally upload a new avatar",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user with avatar",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "email",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "phone",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Avatar image",
                        "name": "avatar",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.UserUpdateSuccessResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.UserUpdateFailResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/services.UserUpdateFailResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/services.UserUpdateFailResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "services.AuthLoginData": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string",
                    "example": "admin"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user_id": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "services.AuthLoginFailResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid credentials"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.AuthLoginParamRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "andrerafli83@gmail.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "services.AuthLoginSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/services.AuthLoginData"
                },
                "message": {
                    "type": "string",
                    "example": "Login successful"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Vitamin"
                }
            }
        },
        "services.CategoryCreateData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Vitamin"
                }
            }
        },
        "services.CategoryCreateFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid parameter"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.CategoryCreateSuccessResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/services.CategoryCreateData"
                },
                "message": {
                    "type": "string",
                    "example": "Category created successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.CategoryDeleteFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to delete category"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.CategoryDeleteSuccessResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Category deleted successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.CategoryFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to fetch categories"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.CategorySuccessResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.Category"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Categories fetched successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.CategoryUpdateData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Vitamin"
                }
            }
        },
        "services.CategoryUpdateFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid parameter"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.CategoryUpdateSuccessResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/services.CategoryUpdateData"
                },
                "message": {
                    "type": "string",
                    "example": "User updated successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.DashboardData": {
            "type": "object",
            "properties": {
                "chart_activity_data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "low_stock": {
                    "type": "integer",
                    "example": 50
                },
                "no_stock": {
                    "type": "integer",
                    "example": 10
                },
                "product_total": {
                    "type": "integer",
                    "example": 100
                },
                "stock_total": {
                    "type": "integer",
                    "example": 5000
                }
            }
        },
        "services.DashboardFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to fetch dashboard data"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.DashboardSuccessResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/services.DashboardData"
                },
                "message": {
                    "type": "string",
                    "example": "Dashboard data fetched successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.Product": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string",
                    "example": "Mie Sedap"
                },
                "category": {
                    "type": "string",
                    "example": "Mie"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image": {
                    "type": "string",
                    "example": "base64imagestring"
                },
                "name": {
                    "type": "string",
                    "example": "Mie Sedap Goreng"
                },
                "sku": {
                    "type": "string",
                    "example": "SKU-20251214201530-042"
                }
            }
        },
        "services.ProductCreateData": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string",
                    "example": "Mie Sedap"
                },
                "category_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image": {
                    "type": "string",
                    "example": "base64imagestring"
                },
                "name": {
                    "type": "string",
                    "example": "Mie Sedap Goreng"
                },
                "price": {
                    "type": "string",
                    "example": "10000"
                },
                "sku": {
                    "type": "string",
                    "example": "SKU-20251214201530-042"
                }
            }
        },
        "services.ProductCreateFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to create product"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.ProductDeleteFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to delete product"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.ProductDeleteSuccessResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Product deleted successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.ProductDetail": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string",
                    "example": "Mie Sedap"
                },
                "category": {
                    "type": "string",
                    "example": "Mie"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image": {
                    "type": "string",
                    "example": "base64imagestring"
                },
                "name": {
                    "type": "string",
                    "example": "Mie Sedap Goreng"
                },
                "price": {
                    "type": "string",
                    "example": "10000"
                },
                "quantity": {
                    "type": "integer",
                    "example": 150
                },
                "sku": {
                    "type": "string",
                    "example": "SKU-20251214201530-042"
                }
            }
        },
        "services.ProductDetailFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to fetch product"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.ProductDetailSuccessResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/services.ProductDetail"
                },
                "message": {
                    "type": "string",
                    "example": "Product fetched successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.ProductFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to fetch product"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.ProductSuccessResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.Product"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Product fetched successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.ProductUpdateData": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string",
                    "example": "Mie Sedap"
                },
                "category_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image": {
                    "type": "string",
                    "example": "base64imagestring"
                },
                "name": {
                    "type": "string",
                    "example": "Mie Sedap Goreng"
                },
                "price": {
                    "type": "string",
                    "example": "10000"
                },
                "sku": {
                    "type": "string",
                    "example": "SKU-000001"
                }
            }
        },
        "services.ProductUpdateFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to update product"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.ProductUpdateSuccessResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/services.ProductUpdateData"
                },
                "message": {
                    "type": "string",
                    "example": "Product updated successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.TransactionCreateData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "move_type": {
                    "description": "IN | OUT",
                    "type": "string",
                    "example": "in"
                },
                "product_id": {
                    "type": "integer",
                    "example": 1
                },
                "quantity": {
                    "type": "integer",
                    "example": 100
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "services.TransactionCreateFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to create transaction"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.TransactionListData": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "ISO 8601 format",
                    "type": "string",
                    "example": "2024-12-14T20:15:30Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "move_type": {
                    "type": "string",
                    "example": "in"
                },
                "pic_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "product_brand": {
                    "type": "string",
                    "example": "Sedap"
                },
                "product_name": {
                    "type": "string",
                    "example": "Mie Sedap Goreng"
                },
                "product_price": {
                    "type": "integer",
                    "example": 5000
                },
                "product_sku": {
                    "type": "string",
                    "example": "MIE001"
                },
                "quantity": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "services.TransactionListFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to fetch transaction"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.User": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "base64imagestring"
                },
                "email": {
                    "type": "string",
                    "example": "andrerafli83@gmail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Andre"
                },
                "phone": {
                    "type": "string",
                    "example": "081234567890"
                },
                "role": {
                    "type": "string",
                    "example": "staff"
                }
            }
        },
        "services.UserCreateData": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "base64imagestring"
                },
                "email": {
                    "type": "string",
                    "example": "andrerafli83@gmail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Andre"
                },
                "phone": {
                    "type": "string",
                    "example": "09999999999"
                },
                "role": {
                    "type": "string",
                    "example": "staff"
                }
            }
        },
        "services.UserCreateFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid credentials"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.UserCreateSuccessResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/services.UserCreateData"
                },
                "message": {
                    "type": "string",
                    "example": "User created successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.UserDeleteFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to delete user"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.UserDeleteSuccessResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "User deleted successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.UserDetail": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "base64imagestring"
                },
                "email": {
                    "type": "string",
                    "example": "andrerafli83@gmail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "joined": {
                    "type": "string",
                    "example": "2025-12-14"
                },
                "name": {
                    "type": "string",
                    "example": "Andre"
                },
                "phone": {
                    "type": "string",
                    "example": "081234567890"
                },
                "role": {
                    "type": "string",
                    "example": "staff"
                }
            }
        },
        "services.UserDetailFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to fetch user"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.UserDetailSuccessResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/services.UserDetail"
                },
                "message": {
                    "type": "string",
                    "example": "User fetched successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.UserListFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Failed to fetch users"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.UserListSuccessResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.User"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Users fetched successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.UserUpdateData": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "base64imagestring"
                },
                "email": {
                    "type": "string",
                    "example": "andrerafli83@gmail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Andre"
                },
                "phone": {
                    "type": "string",
                    "example": "09999999999"
                },
                "role": {
                    "type": "string",
                    "example": "staff"
                }
            }
        },
        "services.UserUpdateFailResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid parameter"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "services.UserUpdateSuccessResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/services.UserUpdateData"
                },
                "message": {
                    "type": "string",
                    "example": "User updated successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" JWT",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "StockLab",
	Description:      "Dokumentasi API StockLab",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
